### ISSUE TITLE
'collections. OrderedDict' object has no attribute 'to'.

### ISSUE THREAD

**Issue by hitzhangyu** [amberwangyili/neurop#1]
HI，
   The work is amazing, but I have a problem using the pretrain_models：**'collections. OrderedDict' object has no attribute 'to'.**
    It seems that only the "model.state_dict()" is provided. Did the author use the “torch.save(model.state_dict(),model_path)”
 instead of "torch.save(model,' save_path')" when saving the model?

**Comment by amberwangyili** [comment]
Thanks very much for your attention!
"Did the author use the “torch.save(model.state_dict(),model_path)” instead of "torch.save(model,' save_path')" when saving the model?" ---- Yes, when saving the model, only model.state_dict() is provided.
The released pretrained weights is not the official version. The official code & model checkpoint with configurations will be released soon.

**Comment by hitzhangyu** [comment]
Thanks for your reply!
