### ISSUE TITLE
About the release date of the code and some questions

### ISSUE THREAD

**Issue by youyuge34** [amberwangyili/neurop#2]
1. When to release the codes and can u share the weights .pth of PPR10K? 
2. Regarding to the network structure, I wonder  it looks like a variant version of CSRnet?  And if we increase the strengths, we won't know the changing effect and its direction (e.g. lighter or darker,  lighter or cooler) until we try?

**Comment by amberwangyili** [comment]
> 1. When to release the codes and can u share the weights .pth of PPR10K?

We are currently updating the Pytorch implementation here https://github.com/amberwangyili/neurop-pytorch. 
(Full version would be released before the end of Sept. Thanks for your patience!)

> 2. Regarding to the network structure, I wonder it looks like a variant version of CSRnet?  

Our main contribution, the neural color operator, is fundamentally different from CSRNet from aspects of both motivation (mimic color operators which have nice controllability with only one adjustable scalar) and design (preserve color operator properties through equivariant mapping so that it could be made simple and effective). Besides, reducing the 32D vector in CSRNet to a scalar value is also non-trivial. Naively replacing 32D vector with a 1D value in CSRNet would clearly lead to a drop in performance. 

> 2. And if we increase the strengths, we won't know the changing effect and its direction (e.g. lighter or darker,  lighter or cooler) until we try?

After fine-tuning the neurOps (combine three operators sequentially and train on the target dataset), the strength scalar is more like an exposed network parameter for us to further adjust the enhancement results. (please refer to the results we provided in the supplemental material)
